# Generated by Django 3.2.12 on 2022-05-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListCross',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='url Cross')),
            ],
            options={
                'verbose_name': 'Cross',
                'verbose_name_plural': 'Cross#',
                'ordering': ['title'],
            },
        ),
    ]
